In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)
print(f"CUDA available: {torch.cuda.is_available()}")

2.11.0+cu128
CUDA available: True


## Introduction to Tensors

### Creating tensors

In [3]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
# Get tensor back as Python int
scalar.item()

7

In [6]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
# MATRIX
MATRIX = torch.tensor([[7, 8],
                      [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
MATRIX.ndim

2

In [11]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [12]:
TENSOR.ndim

3

In [13]:
TENSOR.shape

torch.Size([1, 3, 3])

#### One 3x3 tensor

In [14]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

### Random tensors

Start with random tensors (numbers) -> look at data -> update random tensor -> repeat

In [15]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.3457, 0.7310, 0.4518, 0.6817],
        [0.0243, 0.0029, 0.1354, 0.0995],
        [0.2791, 0.1879, 0.3378, 0.7777]])

In [16]:
random_tensor.ndim

2

In [17]:
# Create random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3, 224, 224)) # colour channels (r,g,b), height, width
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

### Zeros and ones

In [18]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [19]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

### Creating a range of tensors and tensors-like

In [20]:
# Use torch.arange()
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [21]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

In [22]:
# float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # What datatype is the tensor (e.g. float32 or float16)
                               device=None, # What device is your tensor on
                               requires_grad=False) # Whether or not to track gradients with this tensors operations
float_32_tensor.dtype

torch.float32

In [23]:
# float 16 tensor
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [24]:
float_32_tensor * float_16_tensor

tensor([ 9., 36., 81.])

### Getting info from tensors

In [25]:
# Create a tensor
some_tensor = torch.rand(3, 4, dtype=torch.float16)
some_tensor

tensor([[0.3008, 0.5366, 0.3555, 0.5054],
        [0.5366, 0.6519, 0.1567, 0.5107],
        [0.6602, 0.2490, 0.4346, 0.9434]], dtype=torch.float16)

In [26]:
# Find out details about some tensor
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

Datatype of tensor: torch.float16
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating tensors (tensor operations)

In [27]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [28]:
# Multiply by 10
tensor * 10

tensor([10, 20, 30])

In [29]:
# Subtract 10
tensor - 10

tensor([-9, -8, -7])

In [30]:
# PyTorch in-built functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

### Matrix multiplication
Two main ways:
1. Element-wise multiplication
2. Matrix multiplication

Two main rules:
1. The **inner dimensions** must match:
* (3, 2) @ (3, 2) won't work
* (2, 3) @ (3, 2) will work
* (3, 2) @ (2, 3) will work
2. The resulting matrix has the shape of the **outer dimensions**
* (2, 3) @ (3, 2) -> (2, 2)
* (3, 2) @ (2, 3) -> (3, 3)

In [31]:
# Element-wise
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [32]:
# Matrix multiplication
%%time
torch.matmul(tensor, tensor)

CPU times: user 0 ns, sys: 717 µs, total: 717 µs
Wall time: 10 ms


tensor(14)

## Finding the min, max, mean, sum, etc (tensor aggregation)

In [33]:
x = torch.arange(1, 100, 10)
x, x.dtype

(tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91]), torch.int64)

In [34]:
# Find min
torch.min(x), x.min()

(tensor(1), tensor(1))

In [35]:
# Find max
torch.max(x), x.max()

(tensor(91), tensor(91))

In [36]:
# Find mean - note: the torch.mean() function requires a tensor of float32 dtype
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(46.), tensor(46.))

In [37]:
# Find sum
torch.sum(x), x.sum()

(tensor(460), tensor(460))

## Finding the positional min and max

In [38]:
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [39]:
# Find the position in tensor with min or max value
x.argmin(), x.argmax()

(tensor(0), tensor(9))

## Reshaping, stacking, squeezing and unsqueezing tensors


In [40]:
x = torch.arange(1, 10)
x, x.shape

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

In [41]:
# Add an extra dimension
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [42]:
x = torch.arange(1, 13)
x, x.shape

(tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]), torch.Size([12]))

In [43]:
x_reshaped = x.reshape(3, 2, 2)
x_reshaped, x_reshaped.shape

(tensor([[[ 1,  2],
          [ 3,  4]],
 
         [[ 5,  6],
          [ 7,  8]],
 
         [[ 9, 10],
          [11, 12]]]),
 torch.Size([3, 2, 2]))

In [44]:
# Change the view
z = x.view(3, 4)
z, z.shape

(tensor([[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]]),
 torch.Size([3, 4]))

In [45]:
# Changing z changes x, because the view of a tensor shares the same memory address as the original input
z[:, 0] = 5
z, x


(tensor([[ 5,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 5, 10, 11, 12]]),
 tensor([ 5,  2,  3,  4,  5,  6,  7,  8,  5, 10, 11, 12]))

In [46]:
# Stack tensor on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[ 5,  2,  3,  4,  5,  6,  7,  8,  5, 10, 11, 12],
        [ 5,  2,  3,  4,  5,  6,  7,  8,  5, 10, 11, 12],
        [ 5,  2,  3,  4,  5,  6,  7,  8,  5, 10, 11, 12],
        [ 5,  2,  3,  4,  5,  6,  7,  8,  5, 10, 11, 12]])

In [47]:
x_stacked = torch.stack([x, x, x, x], dim=1)
x_stacked

tensor([[ 5,  5,  5,  5],
        [ 2,  2,  2,  2],
        [ 3,  3,  3,  3],
        [ 4,  4,  4,  4],
        [ 5,  5,  5,  5],
        [ 6,  6,  6,  6],
        [ 7,  7,  7,  7],
        [ 8,  8,  8,  8],
        [ 5,  5,  5,  5],
        [10, 10, 10, 10],
        [11, 11, 11, 11],
        [12, 12, 12, 12]])

In [48]:
# torch.squeeze() - removes all single dimensions from a tensor
x = torch.zeros(2, 1, 2, 1, 2)
print(x)
x.size()

tensor([[[[[0., 0.]],

          [[0., 0.]]]],



        [[[[0., 0.]],

          [[0., 0.]]]]])


torch.Size([2, 1, 2, 1, 2])

In [49]:
y = torch.squeeze(x)
print(y)
y.size()

tensor([[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]])


torch.Size([2, 2, 2])

In [50]:
y = torch.squeeze(x, 0)
print(y)
y.size()

tensor([[[[[0., 0.]],

          [[0., 0.]]]],



        [[[[0., 0.]],

          [[0., 0.]]]]])


torch.Size([2, 1, 2, 1, 2])

In [51]:
y = torch.squeeze(x, 1)
print(y)
y.size()

tensor([[[[0., 0.]],

         [[0., 0.]]],


        [[[0., 0.]],

         [[0., 0.]]]])


torch.Size([2, 2, 1, 2])

In [52]:
y = torch.squeeze(x, 3)
print(y)
y.size()

tensor([[[[0., 0.],
          [0., 0.]]],


        [[[0., 0.],
          [0., 0.]]]])


torch.Size([2, 1, 2, 2])

In [53]:
# torch.unsqueeze() - adds a single dimension to a tensor at a specific dim
x_squeezed = x_reshaped.squeeze()
print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# Add an extra dimension with unsqueeze
y = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {y}")
print(f"New shape: {y.shape}")

Previous tensor: tensor([[[ 5,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]],

        [[ 5, 10],
         [11, 12]]])
Previous shape: torch.Size([3, 2, 2])

New tensor: tensor([[[[ 5,  2],
          [ 3,  4]],

         [[ 5,  6],
          [ 7,  8]],

         [[ 5, 10],
          [11, 12]]]])
New shape: torch.Size([1, 3, 2, 2])


In [54]:
# torch.permute() - rearranges the dimensions of a target tensor - note: it return a view (same mem address)
x_original = torch.rand(size=(224, 224, 3)) # height, width, colour_channels

# Permute the original tensor do rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0 -> 1, 1 -> 2, 2 -> 0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}") # colour_channel, height, width

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


## Indexing (selecting data from tensors)
Indexing in PyTorch is similar to indexing in NumPy

In [55]:
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [56]:
# Let's index on the tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [57]:
# Middle bracket (dim=1)
x[0, 0]

tensor([1, 2, 3])

In [58]:
# Let's index on the most inner bracket (last dimension)
x[0, 0, 0]

tensor(1)

In [59]:
# Select 'all' of a target dim
x[:, 1]

tensor([[4, 5, 6]])

In [60]:
# Get all values of 0th and 1st dim but only index 1 of 2nd dim
x[:, :, 1]

tensor([[2, 5, 8]])

In [61]:
# Get all values of the 0th dim but onli the 1 index value of the 1st and 2nd dim
x[:, 1, 1]

tensor([5])

In [62]:
# Get index 0 of 0th and 1st dims and all values of 2nd dim
x[0, 0, :]

tensor([1, 2, 3])

In [63]:
# Index on x to return 3, 6, 9
x[:, :, 2]

tensor([[3, 6, 9]])

## PyTorch tensors and NumPy
* Data in NumPy, want in PyTorch tensor -> torch.from_numpy(ndarray)
* PyTorch tensor -> NumPy -> torch.Tensor.numpy()


In [64]:
# NumPy to tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array) # warning: when converting from numpy -> pytorch, pytorch reflects numpy's default dtype of float64 unless specified otherwise
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [65]:
# Change the value of the array, what happens to tensor
array += 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([2., 3., 4., 5., 6., 7., 8.], dtype=torch.float64))

In [66]:
# Tensor to numpy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility
How neural network learns:
Start with random numbers -> tensor operations -> update random numbers to try and make them better represent the data -> repeat

To reduce the randomness in neural networks and pytorch comes the concept of a **random seed**: 'flavour' the randomness

In [67]:
import torch

random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A == random_tensor_B)

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [68]:
RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED) # Need to call again
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C == random_tensor_D)

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


### Running tensors and PyTorch objects on the GPUs

In [69]:
!nvidia-smi

Thu Jul  9 22:54:06 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.82.07              Driver Version: 580.82.07      CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   39C    P8              9W /   70W |       3MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [70]:
# CHeck for GPU access with PyTorch
import torch
torch.cuda.is_available()

True

For PyTorch since it's capable of running compute on the GPU or CPU, it's best practice to setup device agnostic code: https://docs.pytorch.org/docs/2.13/notes/cuda.html#best-practices
E.g. run on GPU if available, otherwise on CPU

In [71]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [72]:
# Count numeber of GPUs
torch.cuda.device_count()

1

## Putting tensors (and models) on GPU

In [73]:
# Create a tensor (default on CPU)
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [74]:
# Move tensor to GPU if available
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

### Exercises

In [75]:
# 1
x = torch.rand(7, 7)
x

tensor([[0.8694, 0.5677, 0.7411, 0.4294, 0.8854, 0.5739, 0.2666],
        [0.6274, 0.2696, 0.4414, 0.2969, 0.8317, 0.1053, 0.2695],
        [0.3588, 0.1994, 0.5472, 0.0062, 0.9516, 0.0753, 0.8860],
        [0.5832, 0.3376, 0.8090, 0.5779, 0.9040, 0.5547, 0.3423],
        [0.6343, 0.3644, 0.7104, 0.9464, 0.7890, 0.2814, 0.7886],
        [0.5895, 0.7539, 0.1952, 0.0050, 0.3068, 0.1165, 0.9103],
        [0.6440, 0.7071, 0.6581, 0.4913, 0.8913, 0.1447, 0.5315]])

In [76]:
# 2
y = torch.rand(1, 7)
result = torch.matmul(x, y.T)
result, result.shape

(tensor([[1.9625],
         [1.0950],
         [0.9967],
         [1.8910],
         [1.9205],
         [1.0674],
         [1.6949]]),
 torch.Size([7, 1]))

In [77]:
# 3
torch.manual_seed(0)
x = torch.rand(7, 7)

torch.manual_seed(0)
y = torch.rand(1, 7)

result = torch.matmul(x, y.T)
x, y, result, result.shape

(tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
         [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
         [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
         [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
         [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
         [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
         [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]]),
 tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901]]),
 tensor([[1.5985],
         [1.1173],
         [1.2741],
         [1.6838],
         [0.8279],
         [1.0347],
         [1.2498]]),
 torch.Size([7, 1]))

In [78]:
# 4
torch.cuda.manual_seed(1234)

In [79]:
# 5
x = torch.rand(2, 3)
y = torch.rand(2, 3)
x.device, y.device

(device(type='cpu'), device(type='cpu'))

In [80]:
device = "cuda" if torch.cuda.is_available() else "cpu"

torch.manual_seed(1234)
x_to_gpu = x.to(device)

torch.manual_seed(1234)
y_to_gpu = y.to(device)

x_to_gpu.device, y_to_gpu.device

(device(type='cuda', index=0), device(type='cuda', index=0))

In [81]:
# 6
result = torch.matmul(x_to_gpu, y_to_gpu.T)
result, result.shape

(tensor([[0.6131, 1.0917],
         [0.1886, 0.5684]], device='cuda:0'),
 torch.Size([2, 2]))

In [82]:
# 7
torch.max(result), torch.min(result)

(tensor(1.0917, device='cuda:0'), tensor(0.1886, device='cuda:0'))

In [83]:
# 8
result.argmax(), result.argmin()

(tensor(1, device='cuda:0'), tensor(2, device='cuda:0'))

In [84]:
# 9
torch.manual_seed(7)
x = torch.rand(1, 1, 1, 10)
x, x.shape

(tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
            0.3653, 0.8513]]]]),
 torch.Size([1, 1, 1, 10]))

In [87]:
x_squeezed = x.squeeze()
x_squeezed, x_squeezed.shape

(tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
         0.8513]),
 torch.Size([10]))